#!/usr/bin/env perl 

use 5.12.0;
use warnings;

use lib 'lib';
use Disbatch::Web;

Disbatch::Web::init(config_file => 'etc/disbatch/disbatch.json');
Disbatch::Web::limp({workers => 10}, LocalAddr => '0.0.0.0');
