#!/bin/sh
#
# disbatchd init file for starting up the disbatch daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the MongDB daemon that handles all \
#              database requests.

# Generated at Fri Jul 18 09:56:06 2014 with Daemon::Control 0.001

### BEGIN INIT INFO
# Provides:          disbatchd
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: disbatchd
# Description:       Daemon for disbatchd.pl
### END INIT INFO`





if [ -x /etc/disbatch/disbatchd-init ];
then
    /etc/disbatch/disbatchd-init $1
else
    echo "Required program /etc/disbatch/disbatchd-init not found!"
    exit 1;
fi
