#!/bin/sh
#
# disbatch3d init file for starting up the disbatch3 daemon
#
# chkconfig:   - 20 80
# description: Starts and stops the MongDB daemon that handles all \
#              database requests.

# Generated at Fri Jul 18 09:56:06 2014 with Daemon::Control 0.001

### BEGIN INIT INFO
# Provides:          disbatch3d
# Required-Start:    $syslog $remote_fs
# Required-Stop:     $syslog
# Default-Start:     
# Default-Stop:      0 2 3 4 5 1 6
# Short-Description: disbatch3d
# Description:       Daemon for disbatch3d.pl
### END INIT INFO`





if [ -x /etc/disbatch/disbatch3d-init ];
then
    /etc/disbatch/disbatch3d-init $1
else
    echo "Required program /etc/disbatch/disbatch3d-init not found!"
    exit 1;
fi
