#!/usr/bin/env perl

# install nginx before running, restart nginx after running

use 5.12.0;
use warnings;

use File::Slurp;
use Getopt::Long;
use Sys::Hostname;

my ($keyfile, $pemfile, $target);
GetOptions('ssl_certificate_key=s' => \$keyfile, 'ssl_certificate=s' => \$pemfile, 'target=s' => \$target);
$target //= '/etc/nginx/conf.d/default.conf';

my $hostname = hostname;
my (undef, $dc) = split /\./, $hostname;
$keyfile //= "/etc/nginx/mig-$dc.key";
$pemfile //= "/etc/nginx/mig-$dc.pem";

my $config = read_file '/etc/disbatch/nginx-default.conf-example';

for my $file ($keyfile, $pemfile) {
    die "File $file DNE\n" unless -e $file;
}

$config =~ s/disbatch01\.example\.com/$hostname/g;
$config =~ s{/etc/nginx/cert\.pem}{$pemfile};
$config =~ s{/etc/nginx/cert\.key}{$keyfile};

rename $target, "$target-pre-disbatch" if -e $target;
write_file $target, $config;
